name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      fail-fast: false  
      matrix:
        container-engine: [docker, podman]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/prepare-dev
        env:
          CONTAINER_ENGINE: ${{ matrix.container-engine }}

      - name: Run unit tests
        shell: bash
        run: uv run pytest -o env=ENV_FILE=
        env:
          GATEWAY_ORIGIN: http://localhost:9000
          CONTAINER_PROJECT_NAME: getgather-ci
          CONTAINER_SUBNET_PREFIX: 172.24.1
          GETGATHER_APPS: '{"test-app-key":"test-app-name"}'
          HOST_DATA_DIR: ./data
          CONTAINER_ENGINE: ${{ matrix.container-engine }}
          OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          OAUTH_GOOGLE_CLIENT_ID: ${{ secrets.OAUTH_GOOGLE_CLIENT_ID }}
          OAUTH_GOOGLE_CLIENT_SECRET: ${{ secrets.OAUTH_GOOGLE_CLIENT_SECRET }}
          TEST_GITHUB_OAUTH_TOKEN: ${{ secrets.TEST_GITHUB_OAUTH_TOKEN }}
