name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        container-engine: [docker, podman]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/prepare-dev
        env:
          CONTAINER_ENGINE: ${{ matrix.container-engine }}

      - name: Download the environment variables
        uses: ./.github/actions/download-env
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          project: mcp-gateway

      - name: Run unit tests
        shell: bash
        run: uv run pytest -o env=ENV_FILE=
        env:
          CONTAINER_PROJECT_NAME: getgather-ci
          CONTAINER_SUBNET_PREFIX: 172.24.1
          GETGATHER_APPS: '{"test-app-key":"test-app-name"}'
          DATA_DIR: ./data
          CONTAINER_ENGINE: ${{ matrix.container-engine }}
          DEFAULT_PROXY_TYPE: proxy-0
